server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: api-serie
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      username: usr-serie-mongo
      password: pwd-serie-mongo
      database: test
      port: 27017
      host: localhost
      
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
      
info:
  application:
     name: api-serie

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
